lsi:            false
exclude:        ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "scss"]
permalink:      /writing/:title
markdown_ext:   markdown,mkd,mkdn,md
name:           Mohit Sinha's Blog
description:    "The personal site of Mohit Sinha."
url:            http://sinhamohit.com
gems:
  - jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed
